resources/ark.rb

This seems like it's being treated as a download time limit, but "connect timeout" is really a limit on establishing a connection to the server.  Typically if it doesn't happen in ~30s, it's not going to happen at all.
Don't make convergences wait 10m for a connection that isn't going to happen.

Set connect timeout to a rationally short value (30s)

---

recipes/openjdk.rb

RHEL and CentOS 6 have openjdk-1.8.0 packages now. This will also make the cookbook update the alternatives links to the correct bins when using these packages.

add openjdk-1.8.0 bin_cmds

---

Berksfile
README.md
attributes/default.rb
metadata.rb
recipes/homebrew.rb
recipes/set_attributes_from_version.rb

This uses homebrew_cask to add support for Mac OS X. Homebrew requires `Berksfile` to specify `depends` for the homebrew cookbook. If there is a better way to handle this, please let me know! I'd love to get this upstream.

Add support for Mac OS X "mac_os_x" via homebrew.

---

README.md
attributes/default.rb
metadata.rb
providers/alternatives.rb
providers/ark.rb
recipes/oracle.rb
recipes/oracle_i386.rb
resources/alternatives.rb
resources/ark.rb

When one uses java_ark provider in own cookbook to install several javas on a machine, there are 2 issues:
1. The provider removes alternatives configuration before installing alternative for bin cmd. So, if one has another java installed manually, or install several ones using own cookbook, only latest appear in alternatives. Another one issue here is, the latest installed one becomes active in spite of priority and while installation is in progress, the one is being installed is active.
2. #1 can be mitigated by setting default attribute to false. However, if value of 'default' attribute for a resource is false, it forces adding '_alt' suffix for directory name and this cannot be controlled. Therefore, if one decides to switch java installation from one to another, it will install two …

Alternatives improvements

---

.kitchen.yml
README.md
recipes/default.rb
recipes/oracle_rpm.rb
spec/default_spec.rb

Allow Oracle JDK 8 via RPM. Includes a note in the README about the requirement that you maintain your own yum repo for this to actually work since Oracle doesn't provide a public repo for 8. As such, I didn't add a suite to test kitchen since it wouldn't work outside my network. ChefSpec test added, however.

Install Oracle JDK 8 via RPM

---

recipes/windows.rb

Specifying "Java Home" breaks the installation of Java 8 on Windows.  
***Example***
```
default['java']['java_home'] = 'C:\Program Files\Java\jdk1.8.0_45'
```
Several solutions to this problem exist.
In my testing it was sufficient to simply change the appropriate line as such:
```
additional_options = "INSTALLDIR=\"#{java_home_win}\""
```
This made for a backwards compatible change (pre 8, and 8 installer).  I performed validation testing with the installers for 7u45 jre, 8u45 jre, 8u45 jdk.This solution should also simplify the escaped quoting that's occurring.  The above version works with and without spaces in the name.

Java 8 Windows Installer Fix (java_home // INSTALLDIR)

---

.kitchen.yml
metadata.rb
recipes/openjdk.rb
spec/default_spec.rb
test/integration/openjdk-8/bats/verify_openjdk-8.bats

The Ubuntu OpenJDK maintainers have a PPA called "openjdk-r-ppa" which provides OpenJDK 8 for Ubuntu 12.04 and 14.04.
This did require adding 'apt' cookbook as a concrete dependency.
I converged Ubuntu 14.04 manually with no problems, am a little constrained on my kitchen testing capacity with several parallel projects today, but will happily run the full kitchen when I get a chance.
I ran rspec tests, which seemed to pass as much as before, there is a test I patched the output for, "OpenJDK 8", which seems to verify that the chef_run does not fail, but prints "should fail".
I'm happy to write further tests if needed, but wanted to kick open a PR and start a conversation - this is a  block of code I have to add to all of my wrapper cookbooks with consume the java cookbook currently, is a …

Add ubuntu ppa (allows OpenJDK 8)

---

.travis.yml
Gemfile

Test via a complete chef install in Travis vs. doing gem installs which
might not actually match that of the client or server installs.  This is
the preferred test infra install method now.

Update test gems and test via ChefDK

---

README.md

Chef 10 is quite EoL at this point and 100% unsupported.  The minimum
supported chef release for this cookbook should be 11.

Require chef 11

---

.gitignore
chefignore

Use the standard gitignore used in Chef managed cookbooks and add a
chefignore file which limits the files uploaded to the chef server to
speed up chef pulling down the artifacts.

Update gitignore and add a chefignore

---

Berksfile

There's no need to define apt in the berksfile since the berksfile
sources metadata and apt is already in the metadata (also without a
version constraint).

Fix berks url and remove apt

---

recipes/homebrew.rb

Install Java on the Mac OS X with version `node['java']['jdk_version']`

Distinguishing the Java version for installing on the Mac OS X

---

README.md
recipes/windows.rb

I have not added any tests, because it seems like there is no test kitchen for windows set up at the moment and it sounds like a pain to get working.  If you think that we should set up integration tests for windows I am happy to do so?

Set the oracle download terms cookie when installing on Windows.

---

spec/spec_helper.rb

I was playing around looking into this cookbook and noticed that the coverage report wasn't there.
Now when you run `bundle exec rake unit` you'll get a report of the percentage of the unit tests coverage for the cookbook.

Chefspec test coverage report

---

recipes/windows.rb

Chef 12.4.3 throws an error that ruby block must be named

ruby block must be named. 

---

recipes/openjdk.rb

Hi there,
since Ubuntu 15.10 it is no longer needed to include an external ppa-repository for OpenJDK 8. (Ubuntu 16.04 has [OpenJDK 8](http://packages.ubuntu.com/search?keywords=openjdk-8-jdk) in `main` and  [OpenJDK 9](http://packages.ubuntu.com/search?keywords=openjdk-9-jdk) in `universe`).
If you still want to go with the PPA, I would suggest to add an attribute to disable the PPA for everyone who doesn't want to (or can't) use an external PPA.
Cheers,
Jan

Install OpenJDK from distribution if Ubuntu version >= 15.10

---

templates/default/ibm_jdk.installer.properties.erb

Without the LICENSE_ACCEPTED line, installation of IBM JDK 8 appears to be success but nothing is installed on /usr/lib/jvm/java-1.8.0.  Here's the snippet of .kitchen.yml.
...
suites:
- name: default
run_list:
- recipe[java::default]
attributes:
java:
install_flavor: ibm
jdk_version: 8
accept_license_agreement: true
ibm:
accept_ibm_download_terms: true
url: "http://repo.example.com/repo/java/ibm-java-x86_64-sdk-8.0-2.10.bin"
checksum: 1081b8d43bad2942d6cd9662e3d7131542c73522574e897c2ab18a82504e7c99

Updare ibm_jdk.installer.properties.erb for IBM JDK 1.8

---

attributes/default.rb

Attribute ['java']['jdk']['8']['x86_64']['checksum']  was set to JRE instead of JDK checksum.
* JRE Checksum: cc48b4cacfeda1f699b43ea77ddfaa95
* JDK Checksum: 3f3d7d0cd70bfe0feab382ed4b0e45c0

Fix JDK 8 x86_64 Checksum

---

recipes/set_java_home.rb
templates/default/jdk.sh.erb

In the current code the resource [``file '/etc/profile.d/jdk.sh'``](https://github.com/agileorbit-cookbooks/java/blob/c1952dfda48c8fe674cd9124a5f5b2158a47ce7c/recipes/set_java_home.rb#L30-L33) gets executed on every run even when there is no change. The PR is to prevent this unnecessary execution by changing it into a ``template`` resource.

Changes to prevent re-execution of resource creating file jdk.sh

---

attributes/default.rb
metadata.rb
recipes/oracle_jce.rb
recipes/set_attributes_from_version.rb
spec/oracle_jce_spec.rb

This PR adds support for installing the Java Crypto Extensions on Windows. It works roughly similar to the Unix-like support except it relies on the JCE home (aka staging directory) to determine if the JCE Jar files need to be installed. Some other notes
* I've needed to make the cookbook depend on the "windows" cookbook for this to work
* I've added in Chefspec tests to cover as much as I can. I notice there is no current support for Windows in the Test Kitchen file. Adding Windows Test Kitchen support seems like a bigger project best done in a separate PR
* I have not bumped the version in metadata.rb as most cookbook maintainers prefer to do this themselves

Windows JCE support

---

providers/ark.rb
resources/ark.rb

To our corporate blob store needs to we need pass custom get parameters to download files. This change make us to consume this cookbook.

Enable Ark provider to handle URI with get parameters

---

.kitchen.yml
Berksfile
recipes/set_attributes_from_version.rb
test/fixtures/cookbooks/freebsd_bash/metadata.rb
test/fixtures/cookbooks/freebsd_bash/recipes/default.rb

Java 7 on freebsd doesn't work correctly, it assumes you can append `7` to `openjdk` for the package name, but openjdk defaults to version 7, and there is no package named `openjdk7`.
The other changes are to make the bats tests work on freebsd (which defaults to `csh`, not `bash`). The last test in `verify_openjdk-7.bats` fails because it assumes `/usr/bin/jar` but the package creates `/usr/local/bin/jar`.

fix openjdk version logic for freebsd

---

attributes/default.rb

Deprecated features used!
"method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 5 locations:
- /var/chef/cache/cookbooks/java/attributes/default.rb:22:in `from_file'

Resolve chef-12 related warning

---

recipes/homebrew.rb

I was trying to use java 1.41.0 in Test Kitchen using a MacOS VM and got an error from homebrew when installing the default java recipe.  It could not notify log[jdk-version-changed] because it could not find that resource.  Debugging showed that notify.rb is not included by default.rb or homebrew.rb.
Unfortunately there are no public Mac OS X boxcutter images, so I can't update the tests to validate this change, but I did confirm it fixed the problem in my personal Mac OS test kitchen environment.

Mac default converge fails since notify is not included by homebrew

---

README.md
providers/ark.rb
recipes/oracle.rb
resources/ark.rb

Added support for proxy. Usage (from [Examples](https://github.com/agileorbit-cookbooks/java#examples)):
```
name "java"
description "Install Oracle Java"
default_attributes(
"java" => {
"install_flavor" => "oracle",
"jdk_version" => "7",
"oracle" => {
"accept_oracle_download_terms" => true
}
"ark_proxy" => "proxy.example.com:1234"
}
)
run_list(
"recipe[java]"
)
```

Support for proxy

---

recipes/windows.rb

Right now in the windows reciepe one can only download from s3 when they have aws_access_key_id and aws_secret_access_key set. This does not work if one is using an IAM role. 
This changes it so when the s3 bucket name and remote path are set it will trigger the s3 download instead of aws_access_key_id and aws_secret_access_key.

Windows Java can download from s3 only using an IAM profile

---

README.md
recipes/windows.rb

AWS Session Tokens are temporary credentials used for AWS API calls. In secure cloud environments these are commonly used in addition to AWS Access Key ID and AWS Secret Access Key.
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html

Use aws session token for windows java download

---

README.md

Services usually don't have an action `write`. The usually `restart`.
This has nothing to do with subscribing to the `log` resource's `write`action.

Update README: using java::notify

---

recipes/set_java_home.rb
spec/set_java_home_spec.rb

This PR removes 'set-env-java-home' ruby_block:
* `ENV['JAVA_HOME']` within a ruby_block is scoped to that block and causes this resource to be updated on every chef run.
* More importantly: this ruby_block is not used anywhere.
cc: @erichelgeson

Remove useless ruby_block[set-env-java-home]

---

recipes/oracle_jce.rb

The file permissions on the JCE jar files are set to 0664. As a general best practice (and as required by the NIST and DISA STIGs), library files (including jar files) should not be group or world writable and have permissions set to 0755 or less.

Setting appropriate permissions on JCE jar files

---

resources/ark.rb

In chef-client version 13 common existing resource attributes and
methods could not be overwritten in resources, which will raise
exceptions.
This commit removes :retries and :retry_delay attributes from ark
resource to prevent chef-client 13 failures.
Signed-off-by: Josep Lluis Ferrer <jlferrer.riera@gmail.com>

Remove deprecated attributes in ark resource

---

spec/set_attributes_from_version_spec.rb

9.3 is currently the only `freebsd` version in `fauxhai`

Fix set_attributes_from_version test

---

README.md
attributes/default.rb
providers/ark.rb
recipes/oracle_jce.rb

Oracle changed JDK download locations recently causing a global chef-run collapse for those who
don't have their own mirror 💩 . This PR fixes https://github.com/agileorbit-cookbooks/java/issues/422.

Update JDK download URL

---

README.md
attributes/default.rb
recipes/ibm.rb
recipes/ibm_tar.rb
recipes/oracle_rpm.rb

When the `install_flavor` attribute is set to `ibm`, the attributes for
the JDK 6, 7, and 8 `bin_cmds` were not being set. This was caused by an
issue in attribute precedence.
In the `attributes/default.rb` file, the `bin_cmds` attributes were set
based on a case statement which was triggered by the `install_flavor`.
By default, the install flavor is set to `openjdk`. Based on how chef
behaves during the compilation phase, the case statement is triggered
when this attributes file is loaded which means the value of
`install_flavor` will *always* be `openjdk` at that moment so the
conditional branch for `ibm` is never invoked and thus the `bin_cmds`
attributes aren't set. Even if users `force_default` or `override` the
`install_flavor` to be `ibm` in their own cookbook.
This bug was causing …

node `bin_cmds` attr not properly set for ibm java

---

CHANGELOG.md
attributes/default.rb
recipes/oracle.rb
resources/oracle_install.rb

- Update oracle recipe to not perform a switch on java major version and instead
use the version provided in attributes. This allows end users to include new Java
versions without the cookbook requiring an update each time a major version gets
released
- Updated the oracle_install resource to pick up semantic versioning that Oracle
has started using for Java 10+
- Updated the default attributes file to include x86_64 endpoint and checksum for
Oracle Java 10. The i586 version is not (yet) available.
https://github.com/sous-chefs/java/issues/463
https://github.com/sous-chefs/java/issues/460
https://github.com/sous-chefs/java/issues/453
https://github.com/sous-chefs/java/issues/447
The new functionality is not tested as there is no test harness for Oracle Java installation. I assume this is …

Java 10 installation for Linux

---

.kitchen.yml
Berksfile
attributes/default.rb
test/fixtures/cookbooks/test/metadata.rb

Misc Changes:
- updates to get it to converge and pass locally in vagrant, this included changing deprecations to warnings as this was the only way I could test. I am more than happy to revert that change if requested.
Tests:
```$ kitchen verify openjdk-8-ubuntu-1604
-----> Starting Kitchen (v1.22.0)
WARN: Unresolved specs during Gem::Specification.reset:
aws-sdk (~> 2)
ms_rest_azure (~> 0.10.0)
retriable (< 4.0, >= 2.0)
google-cloud-bigquery (~> 1.1)
grpc (< 2.0, >= 1.7.2, ~> 1.0)
google-protobuf (~> 3.0, ~> 3.2, ~> 3.3)
google-cloud-core (~> 1.2)
google-cloud-error_reporting (~> 0.30)
google-cloud-firestore (~> 0.21)
google-cloud-logging (~> 1.5)
google-cloud-pubsub (~> 0.30)
google-cloud-spanner (~> 1.3)
google-cloud-speech (~> 0.29)
google-cloud-trace (~> 0.31)
google-cloud-vision (~> …
```

Update URL for java 8 to 181, the current version is getting a 404

---

.kitchen.yml
resources/certificate.rb
test/fixtures/cookbooks/test/recipes/java_cert.rb
test/fixtures/cookbooks/test/recipes/openjdk6.rb
test/fixtures/cookbooks/test/recipes/openjdk7.rb
test/fixtures/cookbooks/test/recipes/openjdk8.rb
test/fixtures/cookbooks/test/recipes/openjdk_direct.rb
test/fixtures/cookbooks/test/recipes/oracle8.rb
test/fixtures/cookbooks/test/recipes/oracle_direct.rb
test/fixtures/cookbooks/test/recipes/oracle_rpm8.rb

When we use ssl_endpoint, we have a undefined `certout`. 
```bash
kitchen verify oracle-8-debian-8
...
Running handlers:
[2018-07-10T21:01:49+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-07-10T21:01:49+00:00] ERROR: Exception handlers complete
Chef Client failed. 20 resources updated in 57 seconds
[2018-07-10T21:01:49+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2018-07-10T21:01:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-10T21:01:49+00:00] FATAL: NoMethodError: java_certificate[java_certificate_ssl_endpoint] (test::java_cert line 9) had an error: NoMethodError: undefined method `certout' for #<#<Class:0x00000000043b0318>:0x000000000442c7b0>
```

[ssl_endpoint] affect certout

---

resources/oracle_install.rb

Allows for additional Oracle (post 9) jdk download file naming, including '10.0.2'. '18.9', '11'
https://github.com/sous-chefs/java/issues/484

Improve pattern 10plus

---

recipes/openjdk.rb

Signed-off-by: Ben Abrams <me@benabrams.it>
when accessing a node object the accessors much be a string (prefered) or a symbol as people may specify a version as an integer cast the value to a string before accessing the dynamic namespace.
fixes #481 
fixes #463

prevent node access issues when jdk version is a an integer

---

resources/oracle_install.rb

Do a post download checksum of Oracle artifacts
Can't rely on HTTP codes since they don't use them properly on all
errors
Using existing verification functions, adds a post-download verification of artifacts downloaded directly from Oracle.
#478

Verify artifact after download from Oracle

---

attributes/default.rb

Adds proper JDK 11 support -- There were no bin_cmds for 11 which are used for alternatives

Add JDK-11 support

---

README.md
attributes/default.rb
recipes/windows.rb

Some times are necessary to alter the accepted return code from java installer,
this way i can reuse java cookbook overriding only some attributes.
For now i have to use `edit_resource` as:
```ruby
include_recipe 'java'
edit_resource!(:windows_package, node['java']['windows']['package_name']) do
returns [0, 1603]
end
```
with this little modify i'm able to set the attribute more easily.

Allow overwrite `returns` property of windows_packages.

---

CHANGELOG.md
resources/certificate.rb

SNI support is needed for working connections to CDN providers.
This makes the ssl_endpoint attribute work with CDN providers requiring SNI.
No certificate is provided by the remote endpoint unless a servername is supplied.
https://blog.chrismeller.com/testing-sni-certificates-with-openssl

Add servername for sni support

---

.kitchen.yml
CHANGELOG.md
libraries/helpers.rb
recipes/set_attributes_from_version.rb
resources/certificate.rb
spec/libraries/helpers_spec.rb
spec/set_attributes_from_version_spec.rb
test/fixtures/cookbooks/test/recipes/openjdk11.rb
test/integration/openjdk-11/verify_openjdk-11.rb

Signed-off-by: Eric Millbrandt <emillbrandt@brightcove.com>
Installs OpenJDK on:
- CentOS7
- Ubuntu 16.04
- Ubuntu 18.04

OpenJDK 11 support

---

CHANGELOG.md
attributes/default.rb

Update oracle jdk 8 x86_64 url and checksum
#517

Update default download URL and checksum for oracle jdk 8 x86_64

---

README.md
attributes/default.rb
libraries/helpers.rb
recipes/openjdk.rb
resources/certificate.rb
resources/oracle_install.rb

These are long ago EOL. This removes the attributes and helper method.
Signed-off-by: Tim Smith <tsmith@chef.io>

Remove support for EOL Java 6 / 7

---

CHANGELOG.md

Signed-off-by: Ben Abrams <me@benabrams.it>
Clarifies that we did not intentionally break Ubuntu 14.04 support and merely removed testing and making it clear that any support going forward is what it is. New patches may be considered at the discretion of the reviewer/maintainer but should not have any expectations going forward in terms of support.
We discussed this in slack. If the verbiage needs to be further behind I am more than happy to work through it but currently it gives a false sense of that if someone is on Ubuntu 14.04 they can't use what's currently in master.

clarify ubuntu 14.04 support in the changelog

---

CHANGELOG.md
README.md
attributes/default.rb
metadata.rb
recipes/ibm.rb
recipes/ibm_tar.rb
recipes/windows.rb
resources/adoptopenjdk_install.rb
resources/certificate.rb
resources/jce.rb
resources/oracle_install.rb

This change creates a node attribute default['java']['download_path'] which defaults to Chef::Config[:file_cache_path].  All references to Chef::Config[:file_cache_path] have been replaced by node['java']['download_path'] which allows wrappers to set the value of the download and extract path of the tarball to a location other than Chef::Config[:file_cache_path].  These references were not replaced in spec files.  
This is a resolution to issue 538. The path to download and extract the tarball was hardcoded to  Chef::Config[:file_cache_path] which caused failures at my organization due to a 500 mb partition sizing for /var/chef across the organization.  
Note:  All tests did not pass on the master branch prior to modifying the code, so similar tests failed when running the same tests …

Fix for issue 538 to paramaterize file_cache_path references

---

CHANGELOG.md
attributes/default.rb

Updates to the latest corretto builds provided by amazon: 
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

Update Amazon Corretto to 8.222.10.1 and 11.0.4.11.1

---

CHANGELOG.md
resources/certificate.rb

In testing openjdk 11 with this java cookbook I found that the regex used to determine if a cacert is installed and should be deleted before being re-added incorrectly matches similarly named cacerts. Cert comapanyenterpriserootca2 is matching another cert called comapanyenterpriserootca2.1 see https://rubular.com/r/ITi0qdT26D6RWg for broken example.  The certificate resource then attempts to delete comapanyenterpriserootca2 which doesn't exist and fails with fatal error "Error deleting existing certificate comapanyenterpriserootca2".  See https://rubular.com/r/iF81EPJjw7d8Sv for the proposed fixed example"

Fixed java_certificate regex where it checks if cert exists in cacert file

---

CHANGELOG.md
attributes/default.rb
recipes/homebrew.rb

Makes the Cask name into an attribute so can opt for different java install (`java` vs. `adoptopenjdk`) ... solves the problem where `java` went behind Oracle login wall and inches towards to using AdoptOpenJDK.
https://github.com/sous-chefs/java/issues/544
MacOS machine ... so that has some annoying nuances.

Make Homebrew Cask into an attribute

---

attributes/default.rb

Use latest stable openjdk 8
stale adoptopenjdk8 #579

use latest adoptopenjdk8 stable as of 2019-11-22

---

README.md

The readme states that the default openjdk version that gets installed is 6, but when I run the default recipe without changing any attributes version 8 gets installed.
```
* apt_package[openjdk-8-jdk, openjdk-8-jre-headless] action install
- install version 8u232-b09-0ubuntu1 of package openjdk-8-jdk
- install version 8u232-b09-0ubuntu1 of package openjdk-8-jre-headless
```

Update readme with default openjdk version

---

CHANGELOG.md
kitchen.dokken.yml
kitchen.yml
libraries/adopt_openjdk_helpers.rb
resources/adoptopenjdk_linux_install.rb
test/integration/adoptopenjdk/controls/verify_adoptopenjdk.rb

Attempts to fix the JAVA_HOME on Linux for AdoptOpenJDK
This does not contain an extra test for the variable as it doesn't get set correctly in Dokken/Docker.
I can confirm that adding a test in for vagrant, this does actually work. 
Partly #598

[598] JAVA_HOME on Linux (AdoptOpenJDK)

---

CHANGELOG.md
documentation/resources/openjdk_install.md
documentation/resources/openjdk_pkg_install.md
documentation/resources/openjdk_source_install.md
metadata.rb
resources/adoptopenjdk_linux_install.rb
resources/adoptopenjdk_macos_install.rb
resources/alternatives.rb
resources/certificate.rb
resources/openjdk_install.rb
resources/openjdk_pkg_install.rb
resources/openjdk_source_install.rb

Indent all the resources and their options by 2 spaces.
This makes it more readable and take up way less screen space.
Plus it doesn't take so long to organise, so we're more likely to do it.

Add openjdk_source_install resource and documentation

---

recipes/openjdk.rb

Documentation links to `openjdk_install` but error says `adoptopenjdk_install` - I think this typo was introduced in this very large PR:
https://github.com/sous-chefs/java/pull/591/files
Clearing up confusion for users.
I don't think there are any... 🙏

Fix typo (I think...)

---

CHANGELOG.md
resources/certificate.rb
test/fixtures/cookbooks/test/recipes/java_cert.rb

Signed-off-by: Joshua Colson <joshua.colson@gmail.com>
Fix for broken `:remove` action in `java_certificate` resource
#617

[GH-617] - fix broken :remove action on java_certificate

---

CHANGELOG.md
kitchen.dokken.yml
kitchen.yml
resources/adoptopenjdk_install.rb
resources/adoptopenjdk_linux_install.rb
resources/adoptopenjdk_macos_install.rb
resources/alternatives.rb
resources/corretto_install.rb
resources/jce.rb
resources/openjdk_install.rb
resources/openjdk_pkg_install.rb
resources/openjdk_source_install.rb

Chef Infra Client 16 needs provides and Chef Infra Client < 16 needs resource_name here. If we support both then we need both.
Signed-off-by: Tim Smith <tsmith@chef.io>

Restore Chef Infra Client < 16 compatibility

---

CHANGELOG.md
libraries/corretto_helpers.rb
spec/libraries/corretto_helpers_spec.rb

Adds ARM64 installation for corretto

Add aarch64 systems for corretto installation

---

.github/workflows/ci.yml
CHANGELOG.md
kitchen.dokken.yml
kitchen.yml
libraries/openjdk_helpers.rb
resources/openjdk_install.rb
resources/openjdk_source_install.rb
test/integration/openjdk/controls/verify_openjdk.rb

This actually fixes two issues:
- Properly fix `resource_name` and `provides` parameters in
`openjdk_source_install` resource as `openjdk_source_install`.
- Use `new_resource.install` when references parameters in `openjdk_install`
This resolves #645.
Signed-off-by: Lance Albertson <lance@osuosl.org>

If installation issues with openjdk_install resource

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
kitchen.yml
libraries/certificate_helpers.rb
libraries/corretto_helpers.rb
resources/certificate.rb
spec/libraries/certificate_helpers_spec.rb
spec/libraries/corretto_helpers_spec.rb
spec/spec_helper.rb

Adds Amazon Corretto 15 support
Adds configurable file cache property to `java_certificate`
Adds `cacerts` property for interacting with java cacerts file for Java 9+

Adds Amazon Corretto 15 support, changes to `java_certificate`

---

.github/workflows/ci.yml
.github/workflows/md-links.yml

ActionsHub is deleting the master branch
Use the v2 checkout action rather than master
ActionsHub is deleting their master branch

Change the ActionsHub from the master to main branch

---

CHANGELOG.md
documentation/resources/corretto_install.md
libraries/corretto_helpers.rb
metadata.rb
resources/adoptopenjdk_install.rb
resources/adoptopenjdk_linux_install.rb
resources/adoptopenjdk_macos_install.rb
resources/alternatives.rb
resources/certificate.rb
resources/corretto_install.rb
resources/jce.rb
resources/openjdk_install.rb
resources/openjdk_pkg_install.rb
resources/openjdk_source_install.rb

- Remove Corretto checksum code defaults as this changes regularly,
and is not provide in the SHA256 format via an API
- Set unified_mode to true for Chef 17 support
- Bump the minimum Chef version to 15.3 for unified_mode support
- Corretto checksums fail tests regularly

unified_mode & Corretto checksum fixes

---

CHANGELOG.md
test/integration/adoptopenjdk/controls/verify_adoptopenjdk.rb
test/integration/custom-package/controls/verify_home.rb
test/integration/remove-adoptopenjdk/controls/verify_adoptopenjdk-removal.rb

Hey!
I ran Cookstyle 7.16.1 against this repo and here are the results.
This repo was selected due to the topics of chef-cookbook
- 1:11 warning: `InSpec/Deprecations/AttributeHelper` - InSpec attributes have been renamed to inputs. Use the `input` method not the deprecation `attribute` method to access these values. (https://docs.chef.io/workstation/cookstyle/inspec_deprecations_attributehelper)
- 2:16 warning: `InSpec/Deprecations/AttributeHelper` - InSpec attributes have been renamed to inputs. Use the `input` method not the deprecation `attribute` method to access these values. (https://docs.chef.io/workstation/cookstyle/inspec_deprecations_attributehelper)
- 3:31 warning: `InSpec/Deprecations/AttributeHelper` - InSpec attributes have been renamed to inputs. Use the `input` method not …

Automated PR: Cookstyle Changes

---

CHANGELOG.md
documentation/resources/adoptopenjdk_install.md
documentation/resources/adoptopenjdk_macos_install.md
resources/adoptopenjdk_install.rb
resources/adoptopenjdk_macos_install.rb

Remove brew tap --full as it is no longer a valid option
MacOS doesn't currently converge.

Remove brew tap --full option

---

.github/workflows/test-kitchen.yml

Add Cookstyle back into the required checks
Cookstyle doesn't actually run in 0.0.1 of the check

Add Cookstyle back into the required checks

---

CHANGELOG.md
metadata.rb
resources/adoptopenjdk_install.rb
resources/adoptopenjdk_linux_install.rb
resources/adoptopenjdk_macos_install.rb
resources/alternatives.rb
resources/certificate.rb
resources/corretto_install.rb
resources/jce.rb
resources/openjdk_install.rb
resources/openjdk_pkg_install.rb
resources/openjdk_source_install.rb
resources/partial/_common.rb
resources/partial/_java_home.rb
resources/partial/_linux.rb
resources/partial/_macos.rb

- Require Chef 16 for resource partials
- Add resource partials for: MacOS, Linux, Java Home and Common as these are used in a multiple places
List any existing issues this PR resolves

Resource partials

---

.github/workflows/test-kitchen.yml
CHANGELOG.md
spec/libraries/adopt_openjdk_helpers_spec.rb

This will allow the reusable workflow to post problems back to the open
PR
Signed-off-by: Dan Webb <dan.webb@damacus.io>

Elevate permissions for GitHub reusable workflow

---

.github/workflows/test-kitchen.yml
CHANGELOG.md
kitchen.yml
libraries/corretto_helpers.rb
spec/libraries/corretto_helpers_spec.rb

- Remove Correto 15 and 16
- Add Corretto 17 and 18
- Change the default download URL for Corretto to the versioned resources URL, rather than the latest.
Using the versioned URL should now fix #628

Update Corretto URLs

---

.github/workflows/test-kitchen.yml
kitchen.dokken.yml

Remove Debian 9 which is now EOL. As a result, no packages can be installed on the system breaking CI.

Use standard dokken file and remove EOL Debian 9

---

CHANGELOG.md
resources/openjdk_source_install.rb

Fix typo in `openjdk_source_install`
https://github.com/sous-chefs/java/issues/701

fix: typo, 'opendjdk' should be 'openjdk'

---

CHANGELOG.md
resources/openjdk_pkg_install.rb

Allows to have version locked openjdk installs from packages.
https://github.com/sous-chefs/java/issues/711

[GH-711] Fix openjdk_pkg_install to obey pkg_version property for all pkg_names
