attributes/default.rb
Signed-off-by: Gregor Zurowski <gregor@zurowski.org>
=> Update Oracle JDK7 to version 7u75

recipes/oracle.rb, recipes/oracle_i386.rb
=> Make sure tar package installed for java_ark

recipes/windows.rb
Please merge ASAP :dancers:
:smiley:
=> Fixes #257 Changed switches for the jdk 8 exe installer on windows

recipes/default.rb
I am not sure why exactly this is here. I think we would all much rather
Chef to simply fail convergence.
=> Fixes #155 to allow install of OpenJDK 1.8.

attributes/default.rb
Updated the jdk version from 8u40 to 8u45
=> Updated Oracle JDK to 8u45

libraries/matchers.rb
Added java_alternatives unset action and java_ark install and remove actions to ChefSpec matchers.
=> Added ChefSpec matchers

recipes/oracle_rpm.rb
I'm not sure if the API changed, but the current code uses the syntax fatal!( <MESSAGE> ).
See https://github.com/chef/chef/blob/master/lib/chef/application.rb
=> Fix compile error using Chef::Application.fatal

attributes/default.rb, providers/ark.rb, recipes/oracle.rb, resources/ark.rb
=> Provide possibility to set ark download timeout

README.md, attributes/default.rb, libraries/helpers.rb, recipes/default.rb, recipes/ibm.rb, recipes/ibm_tar.rb, recipes/openjdk.rb, recipes/oracle_i386.rb, recipes/set_java_home.rb, spec/libraries/helpers_spec.rb
Also remove our employees from the current author lists and update
copyrights that haven't been bumped in a while
=> dUpdate opscode -> chef software

README.md
=> Added travis badge in README.md

metadata.rb
=> Add source and issues urls

README.md
This allows for all the needed attributes to be visible in one
spot.
=> Add JDK checksum attribute to `README.md`

README.md, recipes/homebrew.rb, recipes/ibm.rb, recipes/ibm_tar.rb, recipes/notify.rb, recipes/openjdk.rb, recipes/oracle.rb, recipes/oracle_i386.rb, recipes/oracle_rpm.rb, recipes/windows.rb, spec/ibm_spec.rb, spec/ibm_tar_spec.rb, spec/openjdk_spec.rb, spec/oracle_i386_spec.rb, spec/oracle_rpm_spec.rb, spec/oracle_spec.rb, spec/windows_spec.rb
=> Add notification for other chef resources to subscribe to.

README.md, attributes/default.rb, recipes/windows.rb
=> Support removal of obsolete JREs via optional attribute

.github/lock.yml
=> Add LockBot

resources/certificate.rb
this was supposed to be in #487 but somehow didnt get committed.
fixes #451
=> make cert alias matching case insensitive

README.md, resources/jce.rb, spec/oracle_jce_spec.rb
Signed-off-by: Noel Georgi <git@frezbo.com>
Fixes #491
=> Fixes #491

CHANGELOG.md, metadata.rb
Prep for release, updated changelog and version bump as major.
=> prep for v3.0.0 release

resources/jce.rb
Signed-off-by: Noel Georgi <git@frezbo.com>
Fixes JCE installation on linux. @tas50 Could this be merged and a new release chartered?. Thanks
=> Fix jce installation linux

CHANGELOG.md, metadata.rb, recipes/set_attributes_from_version.rb, resources/jce.rb, spec/set_attributes_from_version_spec.rb
-Set java home on macosx using /usr/libexec/java_home
-Find command should have ./ for path to search, works for nix and mac
=> Fix mac osx issues with java home and jce

CHANGELOG.md
* Changelog updated.
* Version previously updated.
Should be ready for release?
=> Release v3.1.2

Dangerfile
=> Stop failing on missing PR labels

CHANGELOG.md, metadata.rb
Signed-off-by: Ben Abrams <me@benabrams.it>
Prep for release
Java downloads
=> prep for v3.2.0 release

README.md
README: update build status to use circleci
=> README: update build status to use circleci

.kitchen.dokken.yml, .kitchen.yml
Modernize what we test on a bit.
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Remove Ubuntu 14.04 testing and update Fedora to 29

recipes/purge_packages.rb
We warned that we'd remove this in the next major and then we never did
Signed-off-by: Tim Smith <tsmith@chef.io>
=> Remove the empty purge_packages recipe

CHANGELOG.md, attributes/default.rb, resources/jce.rb, resources/oracle_install.rb
Updating the Oracle JDK 8 url and checksum again.
=> Fixing oracle jdk 8 url and updating to 8u202.

CHANGELOG.md, metadata.rb, spec/set_attributes_from_version_spec.rb
Signed-off-by: Ben Abrams <me@benabrams.it>
Fixing windows specs
=> Try fixing windows specs

CHANGELOG.md, metadata.rb, resources/oracle_install.rb, spec/openjdk_spec.rb, spec/set_attributes_from_version_spec.rb
=> release 4.0.0

CHANGELOG.md, metadata.rb
=> release 4.1.0

.circleci/config.yml, .github/lock.yml, .kitchen.dokken.yml, .kitchen.macos.yml, .kitchen.yml, .mdlrc, .rubocop.yml, .yamllint, CHANGELOG.md, README.md, TESTING.md, test/integration/adoptopenjdk/attributes/adoptopenjdk-10-hotspot.yml, test/integration/adoptopenjdk/attributes/adoptopenjdk-10-openj9.yml, test/integration/adoptopenjdk/attributes/adoptopenjdk-11-hotspot.yml, test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9-large-heap.yml, test/integration/adoptopenjdk/attributes/adoptopenjdk-11-openj9.yml, test/integration/adoptopenjdk/attributes/adoptopenjdk-8-openj9.yml, test/integration/adoptopenjdk/inspec.yml, test/integration/remove-adoptopenjdk/inspec.yml
required terraform change https://github.com/sous-chefs/terraform-github-org/pull/180
=> circleci orb v2 - yamllint, mdl

CHANGELOG.md, metadata.rb
Update CHANGELOG and metadata for 4.3.0 release
n/a
=> Update CHANGELOG and metadata for 4.3.0 release

resources/adoptopenjdk_install.rb
=> Auto correct using cookstyle

README.md
Make sure the link works from github
=> Fix link to adoptopenjdk resource

.github/workflows/ci.yml, CHANGELOG.md, Dangerfile, README.md, documentation/resources/openjdk_install.md, documentation/resources/openjdk_pkg_install.md, kitchen.dokken.yml, kitchen.yml, libraries/openjdk_helpers.rb, metadata.rb, recipes/homebrew.rb, resources/openjdk_pkg_install.rb, spec/spec_helper.rb, test/fixtures/cookbooks/test/recipes/openjdk_pkg.rb, test/integration/openjdk_pkg/controls/verify_openjdk.rb, test/integration/openjdk_pkg/inspec.yml
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
add openjdk_pkg_install resource/documentation/tests
=> add openjdk_pkg_install resource/documentation/tests

CHANGELOG.md, README.md, documentation/resources/adoptopenjdk_install.md, documentation/resources/adoptopenjdk_linux_install.md, documentation/resources/adoptopenjdk_macos_install.md, resources/adoptopenjdk_install.rb, resources/adoptopenjdk_macos_install.rb
Add documentation for 
- adoptopenjdk_macos_install
- adoptopenjdk_macos_install
- adoptopenjdk_linux_install
=> Add documentation for new resources

test/integration/adoptopenjdk/controls/verify_adoptopenjdk.rb
Simplify the version matching test
This fixes the MacOS tests
None
=> Simplify the version matching test

.github/workflows/ci.yml
Uses full actions instead of workflows where possible
=> Use Full Actions instead of workflows

README.md
Remove Oracle/IBM from the Readme
#622
=> Remove Oracle/IBM from the Readme

.github/workflows/ci.yml, .github/workflows/delivery.yml, .github/workflows/final.yml, .github/workflows/integration-complete.yml, .github/workflows/md-links.yml, CHANGELOG.md
=> Make workflow runs wait for workflow runs

CHANGELOG.md
Describe what this change achieves
List any existing issues this PR resolves
=> Revert CHANGELOG to 11.2.2

CHANGELOG.md, documentation/resources/openjdk_install.md, kitchen.dokken.yml, kitchen.global.yml
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook
=> Automated PR: Standardising Files

CHANGELOG.md, resources/openjdk_pkg_install.rb
- **fix missing skip_alternatives**
=> skip alternatives patch

CHANGELOG.md, documentation/resources/openjdk_pkg_install.md, documentation/resources/temurin_package_install.md, resources/openjdk_pkg_install.rb, resources/openjdk_source_install.rb, resources/temurin_package_install.rb
Signed-off-by: Dan Webb <dan.webb@damacus.io>
=> Airgap mode and alternative URLs for repository addresses
